import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React from "react";
import type {Metadata} from "next";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Next - Tic Tac Toe",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={"text-zinc-50"}>
            <header>
                <nav className="flex bg-gradient-to-r from-emerald-700 to-green-900">
                    <div className="flex items-center p-2">
                        <img src="assets/images/logo-new.webp" className="w-12" alt="Logo"/>
                        <div className="font-bold text-2xl ml-0.5">
                            PI<span className="text-black">AIC</span>
                        </div>
                    </div>

                    <div className="flex-1 flex items-center justify-end">
                        <Link href={'/login'} className="menu-item">
                            <span>Login</span>
                        </Link>
                        <div className="menu-item group">
                            <span>Team</span>
                            <div
                                className="group-hover:block hidden absolute top-full right-0 rounded-b-md bg-green-900">
                                <div
                                    className="flex p-4 hover:bg-white/5 hover:text-zinc-300 transition-colors ease-in-out whitespace-nowrap items-center justify-end">
                                    <span>Team Alpha</span>
                                </div>
                                <div
                                    className="flex p-4 hover:bg-white/5 hover:text-zinc-300 transition-colors ease-in-out whitespace-nowrap items-center justify-end">
                                    <span>Team Beta</span>
                                </div>
                            </div>
                        </div>
                        <Link href={"/game"} className="menu-item">
                            <span>Game</span>
                        </Link>
                        <div className="menu-item">
                            <span>Contact</span>
                        </div>
                    </div>
                </nav>
            </header>
            <main className={"flex min-h-screen flex-col items-center justify-center p-24"}>
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
